# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cae0f60aa1b85a072e7eb920dd942821a0cb817862555bc17fe22224e3ba1b913b7a6e2e8f4bfd460fb6e16ea11039e391395e1a3e8422e391dc7103a91cdc64

test:
  secret_key_base: 04aa2deca01a0dc023b294765369d07e4eed5e4d996cba6341ca376c9bb8c6d8d2efc95b62d7d87f9e0bcfce9af72dd450671a70be88d64275b138064e3148fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
